### ISSUE TITLE
centimeters to meters is /100

### ISSUE THREAD

**Issue by copypasteearth** [Kleak/international_system_of_units#26]
in your length conversion to meters when the num is in centimeters should be decided by 100

**Expected behavior**
converting centimeters to meters should result in meters.

**Comment by kevin-sakemaer** [comment]
Oops that's right thanks for catching it! Will fix this when I'm in front of my computer.

**Comment by kevin-sakemaer** [comment]
the version on pub has been updated also.
https://pub.dev/packages/international_system_of_units
